server:
  port: 8761
eureka:
  instance:
    hostname: eureka8761.com
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
#      defaultZone: http://eureka8762.com:8762/eureka/
      defaultZone: http://eureka8761.com:8761/eureka/

