server:
  port: 7001

spring:
  application:
    name: order-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud2021?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka8761.com:8761/eureka #,http://eureka8762.com:8762/eureka

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wengxs.entity

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 2000
  circuitbreaker:
    enabled: true # 开启降级、熔断