server:
  port: 8762
eureka:
  instance:
    hostname: eureka8762.com
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka8761.com:8761/eureka/

